### ISSUE TITLE
Multiline string support

### ISSUE THREAD

**Issue by bruce** [nikolauska/toml_elixir#1]
First of all, thank you for writing this package; it's fantastic!

One thing I've run into lately and I'd like to suggest as a feature is multiline strings, as defined near the end of the [String](https://github.com/toml-lang/toml#user-content-string) section of the spec, supporting use of `"""` (escapable) and `'''` (literal) string delimiters. While normal strings work for multiline, it would be nice to have these to limit the need for quote escaping.

Thanks again for your hard work on this handy project!

**Comment by nikolauska** [comment]
I will try to implement this for next version

**Comment by nikolauska** [comment]
Version 2.0.0 has now been release which adds support for multiline strings
